"use client";

import Link from "next/link";
import { ArrowRight, Sparkles, ChefHat, Bot } from "lucide-react";

const Hero = () => {
    return (
        <section className="bg-gradient-to-br from-orange-50 via-white to-emerald-50">
            <div className="max-w-7xl mx-auto px-4 md:px-8 py-16 lg:py-24">

                <div className="grid lg:grid-cols-2 gap-12 items-center">

                    {/* Left Side */}
                    <div>

                        <span className="inline-flex items-center gap-2 bg-orange-100 text-orange-600 px-4 py-2 rounded-full text-sm font-medium">
                            <Sparkles size={16} />
                            AI Powered Recipe Assistant
                        </span>

                        <h1 className="mt-6 text-4xl md:text-5xl lg:text-6xl font-bold leading-tight text-gray-900">
                            Cook Smarter with
                            <span className="text-orange-500"> AI </span>
                            Magic
                        </h1>

                        <p className="mt-6 text-gray-600 text-lg leading-8 max-w-xl">
                            Discover delicious recipes, generate meals from your
                            available ingredients, and get instant cooking help
                            with RecipeGenie AI.
                        </p>

                        <div className="mt-8 flex flex-wrap gap-4">

                            <Link
                                href="/recipes"
                                className="bg-orange-500 hover:bg-orange-600 text-white px-6 py-3 rounded-xl flex items-center gap-2 transition"
                            >
                                Explore Recipes
                                <ArrowRight size={18} />
                            </Link>

                            <Link
                                href="/ai-generator"
                                className="border border-orange-500 text-orange-500 hover:bg-orange-50 px-6 py-3 rounded-xl transition"
                            >
                                Generate Recipe
                            </Link>

                        </div>

                    </div>

                    {/* Right Side */}
                    <div className="grid gap-5">

                        <div className="bg-white rounded-3xl shadow-lg p-6 border">

                            <div className="flex items-center gap-4">

                                <div className="bg-orange-100 p-4 rounded-2xl">
                                    <ChefHat className="text-orange-500" />
                                </div>

                                <div>
                                    <h3 className="font-bold text-lg">
                                        AI Recipe Generator
                                    </h3>

                                    <p className="text-gray-500">
                                        Turn your ingredients into delicious recipes.
                                    </p>
                                </div>

                            </div>

                        </div>

                        <div className="bg-white rounded-3xl shadow-lg p-6 border">

                            <div className="flex items-center gap-4">

                                <div className="bg-emerald-100 p-4 rounded-2xl">
                                    <Bot className="text-emerald-500" />
                                </div>

                                <div>
                                    <h3 className="font-bold text-lg">
                                        AI Cooking Assistant
                                    </h3>

                                    <p className="text-gray-500">
                                        Ask questions and get instant cooking advice.
                                    </p>
                                </div>

                            </div>

                        </div>

                        <div className="bg-orange-500 rounded-3xl p-8 text-white shadow-lg">

                            <h2 className="text-4xl font-bold">
                                10K+
                            </h2>

                            <p className="mt-2">
                                Recipes Generated by AI
                            </p>

                        </div>

                    </div>

                </div>

            </div>
        </section>
    );
};

export default Hero;