const TermsPage = () => {
    return (
        <div className="min-h-screen bg-orange-50 px-5 py-16">

            <div className="max-w-4xl mx-auto bg-white rounded-3xl shadow-xl p-8 md:p-12">

                <h1 className="text-4xl font-bold text-orange-500 mb-6">
                    Terms & Conditions
                </h1>


                <p className="text-gray-600 leading-8 mb-6">
                    Welcome to RecipeGenie AI. By accessing or using our
                    platform, you agree to follow these Terms & Conditions.
                    Please read them carefully before using our services.
                </p>



                <section className="space-y-6">


                    <div>
                        <h2 className="text-2xl font-semibold">
                            1. Use of RecipeGenie
                        </h2>

                        <p className="text-gray-600 mt-2 leading-7">
                            RecipeGenie provides AI-generated recipes,
                            cooking suggestions, and food-related information.
                            The recipes are created with the help of artificial
                            intelligence and should be considered as suggestions
                            rather than professional cooking advice.
                        </p>
                    </div>



                    <div>
                        <h2 className="text-2xl font-semibold">
                            2. User Accounts
                        </h2>

                        <p className="text-gray-600 mt-2 leading-7">
                            Users are responsible for maintaining the security
                            of their accounts and providing accurate information
                            during registration. You must not use another
                            person's account without permission.
                        </p>
                    </div>




                    <div>
                        <h2 className="text-2xl font-semibold">
                            3. AI Generated Content
                        </h2>

                        <p className="text-gray-600 mt-2 leading-7">
                            Recipes generated by RecipeGenie AI may contain
                            mistakes or variations. Users should verify
                            ingredients, cooking methods, and allergy-related
                            information before preparing any recipe.
                        </p>
                    </div>




                    <div>
                        <h2 className="text-2xl font-semibold">
                            4. User Reviews
                        </h2>

                        <p className="text-gray-600 mt-2 leading-7">
                            Users may submit reviews and feedback about their
                            experience. Reviews should be respectful and should
                            not contain harmful, offensive, or misleading
                            content.
                        </p>
                    </div>




                    <div>
                        <h2 className="text-2xl font-semibold">
                            5. Saved Recipes
                        </h2>

                        <p className="text-gray-600 mt-2 leading-7">
                            Users can save recipes for personal use. RecipeGenie
                            does not guarantee permanent availability of saved
                            content in case of technical issues or maintenance.
                        </p>
                    </div>




                    <div>
                        <h2 className="text-2xl font-semibold">
                            6. Privacy
                        </h2>

                        <p className="text-gray-600 mt-2 leading-7">
                            We respect user privacy and only collect information
                            necessary to provide our services. Please review our
                            Privacy Policy for more details.
                        </p>
                    </div>




                    <div>
                        <h2 className="text-2xl font-semibold">
                            7. Limitation of Responsibility
                        </h2>

                        <p className="text-gray-600 mt-2 leading-7">
                            RecipeGenie is not responsible for any issues
                            caused by incorrect ingredient usage, allergic
                            reactions, or cooking results. Users should make
                            decisions based on their own judgment.
                        </p>
                    </div>




                    <div>
                        <h2 className="text-2xl font-semibold">
                            8. Changes to Terms
                        </h2>

                        <p className="text-gray-600 mt-2 leading-7">
                            We may update these Terms & Conditions from time
                            to time. Continued use of RecipeGenie after changes
                            means you accept the updated terms.
                        </p>
                    </div>



                </section>



                <div className="mt-10 border-t pt-5 text-gray-500">

                    <p>
                        Last updated: July 2026
                    </p>

                    <p className="mt-2">
                        © RecipeGenie AI. All rights reserved.
                    </p>

                </div>



            </div>


        </div>
    );
};


export default TermsPage;